apiVersion: v1

kind: Secret

metadata:
  name: argus-secret
  namespace: argus

type: Opaque

stringData:

    CAMERA_USERNAME: ""

    CAMERA_PASSWORD: ""

    CAMERA_HOST: ""

    CAMERA_PORT: "554"

    CAMERA_STREAM: "stream1"